name = "ClimaInterpolations"
uuid = "dd0f122e-fa3b-47f3-bcf0-93bbc60d885e"
authors = ["Climate Modeling Alliance"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"

[weakdeps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"

[extensions]
ClimaInterpolationsCUDAExt = "CUDA"

[compat]
Aqua = "0.8"
CUDA = "5.5"
DocStringExtensions = "=0.5, 0.5 - 0.9"
SafeTestsets = "0.1"
Test = "1"
julia = "1.9"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test", "CUDA", "SafeTestsets"]
